# Generated by Django 2.2.5 on 2020-05-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20200503_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='author_id',
        ),
    ]
